name: lint

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install the package
        run: |
          python setup.py develop --no-deps

      - name: Install isort / flake8 / black
        run: |
          pip install isort flake8 black

      - name: Run isort
        run: |
          isort --recursive --check-only chemiwrap

      - name: Run black
        run: |
          black chemiwrap --check

      - name: Run flake8
        run: |
          flake8 chemiwrap
